version: "3.8"

services:
  cortex-id:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cortex-id
    image: cortex-id:latest
    network_mode: host
    ports:
      - "5353:5353/udp"
    environment:
      NODE_NAME: ${HOSTNAME}
    volumes:
      - ~/.cortex:/root/.cortex
    restart: "no"
    tty: true
