version: "3.8"

services:
  cortex-node:
    build:
      context: ../..
      dockerfile: cortex-core/docker/Dockerfile
    container_name: cortex-id
    image: cortex-id:latest
    network_mode: host
    environment:
      NODE_NAME: $(hostname)
    volumes:
      - ~/.cortex:/root/.cortex
    restart: "no"
    tty: true
